import Head from "next/head";
import { Geist, Geist_Mono } from "next/font/google";

import { Grid } from "@mui/material";

import HomePage from "../components/Home";



export default function Home() {
  return (
    <>
      <Head>
        <title>Chef: GoCool</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/logo.png" />
      </Head>
      <div style={{
        width: '100vw',
        height: '100vh'
      }}>
        <HomePage/>
      </div>
    </>
  );
}
